version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
  