version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: travel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_db_network

  # FastAPI Application
  api:
    build: .
    container_name: travel_api
    ports:
      - "8000:8000"
    env_file: 
      - docker.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - shared_db_network

volumes:
  redis_data:

networks:
  shared_db_network: 
    external: true
    name: travel-recharge-database_default
